# Generated by Django 2.0.7 on 2018-07-29 06:57

from django.db import migrations, models
import django.db.models.deletion
import samuv_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('idAtendimento', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica_da_ferida',
            fields=[
                ('idCaracteristica', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('idDoenca', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Ferida',
            fields=[
                ('idFerida', models.AutoField(primary_key=True, serialize=False)),
                ('idDoenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Doenca')),
            ],
            options={
                'verbose_name': 'Ferida',
                'verbose_name_plural': 'Feridas',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('idImagem', models.AutoField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(default='IMG<django.db.models.fields.related.ForeignKey><built-in method now of type object at 0x00007FFABFDE3D60>', max_length=80)),
                ('foto', models.ImageField(upload_to=samuv_web.models.get_image_path, verbose_name=models.CharField(default='IMG<django.db.models.fields.related.ForeignKey><built-in method now of type object at 0x00007FFABFDE3D60>', max_length=80))),
                ('idAtendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('idProfissional', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('idTecnica', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTecnica', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Técnica',
                'verbose_name_plural': 'Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='auth.User')),
                ('nomeUsuario', models.CharField(blank=True, max_length=250, null=True)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.TextField()),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Usuario'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Usuario'),
        ),
        migrations.AddField(
            model_name='doenca',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Paciente'),
        ),
        migrations.AddField(
            model_name='caracteristica_da_ferida',
            name='idFerida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Ferida'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idCaracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Caracteristica_da_ferida'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idDoenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Doenca'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idProfissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Profissional'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idTecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Tecnica'),
        ),
    ]
