# Generated by Django 2.0.7 on 2018-07-29 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import samuv_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 19, 0, 17, 195104)),
        ),
        migrations.AddField(
            model_name='caracteristica_da_ferida',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica_da_ferida',
            name='cor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doenca',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doenca',
            name='tipo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='idCaracteristica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Caracteristica_da_ferida'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='idDoenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Doenca'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='idTecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samuv_web.Tecnica'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(upload_to=samuv_web.models.get_image_path, verbose_name=models.CharField(default='IMG<django.db.models.fields.related.ForeignKey><built-in method now of type object at 0x00007FFAB12F3D60>', max_length=80)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imageName',
            field=models.CharField(default='IMG<django.db.models.fields.related.ForeignKey><built-in method now of type object at 0x00007FFAB12F3D60>', max_length=80),
        ),
    ]
