# Generated by Django 2.0.7 on 2018-07-30 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuv_web', '0004_auto_20180729_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica_da_ferida',
            options={'verbose_name': 'Característica da ferida', 'verbose_name_plural': 'Características das feridas'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 0, 6, 53, 472007)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
